### ISSUE TITLE
Is EXE release possible?

### ISSUE THREAD

**Issue by shevernitskiy** [amPerl/nif#1]
Hey! I know nothing about rust, unfortunatelly. But your project doing exactly what i need (converting nif to gltf). Could you provide realese like an command line exe tool, which can perform convertation with 
 given cmd args (pathes, maybe other possible options)?

**Comment by amPerl** [comment]
hi, sorry, i don't intend to set up binary releases for this project as it's primarily used as a library.

you can, however, pretty easily build this yourself:
- [install rust](https://www.rust-lang.org/learn/get-started)
- run `cargo build --release` in the root directory of this repository
- find your exe in the `target/release` directory
